### PR TITLE
heart responsive and night support

### PR DESCRIPTION
**Pull request by amir28**

### CODE REVIEW

**Comment by imkarimkarim** [comment]
thank you thank you thank you :heart_eyes: 
 really appreciate this ❤️
what is your opinion about default mode? dark or light mode? which one should be default?

**Comment by amir28** [comment]
I prefer light mode for default.

**Comment by imkarimkarim** [comment]
cool :stuck_out_tongue_winking_eye: 
thanks again

**Comment by amir28** [comment]
your welcome :)

**Pull request merged**
