### PR TITLE
twitter and mastodon links added :)

### PR DESCRIPTION
**Pull request by arianmonti**

### CODE REVIEW

**Comment by imkarimkarim** [comment]
thank you that's was a good one.

**Comment by arianmonti** [comment]
Thank you to merge it. I'm not expert at HTML. It will be better if you
improve it :)

**Comment by imkarimkarim** [comment]
Your welcome :) your are my first pull request ever... so thank you.
doesn't need to be expert. it's need to work ;)

**Comment by arianmonti** [comment]
:)

**Pull request merged**
