### PR TITLE
add some content

### PR DESCRIPTION
**Pull request by arianmonti**
I didn't find any suitable fontawesome logo for Aparat and Virgool.
Virgool logo is handwork :) I couldn't find any black and white logo for Virgool :) so it is not visible in dark mode.

### CODE REVIEW

**Comment by imkarimkarim** [comment]
thanks for your interesting contribution :heart_eyes:

**Comment by arianmonti** [comment]
Not at all :wink:

**Comment by arianmonti** [comment]
Not at all :wink:

**Comment by arianmonti** [comment]
Not at all :wink: :wink:

**Comment by arianmonti** [comment]
Not at all :wink: :wink:

**Comment by arianmonti** [comment]
Not at all :wink: :wink:

**Pull request merged**
